In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
df =pd.read_csv("nhentailisttest3.csv")


In [2]:
df.Title[0]

'[Puu no Puupuupuu (Puuzaki Puuna)] Hitozukiai ga Nigate na Miboujin no Yukionna-san to Noroi no Yubiwa [English]'

In [3]:
df[df.Title.str.contains('Puupuupuu')].Title
#df.iloc[1].overview

0    [Puu no Puupuupuu (Puuzaki Puuna)] Hitozukiai ...
2    [Puu no Puupuupuu] Karui Kimochi de Heya ni Ag...
Name: Title, dtype: object

In [4]:
features=['Artist','Tag']
df[features].isnull().sum()

Artist    0
Tag       0
dtype: int64

In [5]:
df['combined_features']= df.Artist+''+df.Tag
df.combined_features.head()
df.iloc[0].combined_features

"['zeroshiki kouichi']['english', 'translated', 'original', 'puu no puupuupuu', 'domination loss', 'sole male', 'big breasts', 'blowjob', 'deepthroat', 'femdom', 'garter belt', 'milf', 'mind control', 'pantyhose', 'sole female', 'stockings', 'widow', 'full color', 'mosaic censorship', 'doujinshi', 'nakadashi', 'leg lock', 'lingerie']"

In [6]:
cv=CountVectorizer()
count_matrix=cv.fit_transform(df.combined_features)
count_matrix.shape #499เรื่อง * 1334 colum

(685, 1677)

In [7]:
cosine_sim=cosine_similarity(count_matrix)
cosine_sim.shape

(685, 685)

In [11]:
print(cosine_sim[:8,:8].round(3)) #roundเอาไว้ดูเศษ

[[1.    0.408 0.602 0.437 0.324 0.344 0.348 0.474]
 [0.408 1.    0.6   0.516 0.419 0.381 0.539 0.437]
 [0.602 0.6   1.    0.6   0.526 0.394 0.478 0.542]
 [0.437 0.516 0.6   1.    0.419 0.381 0.488 0.612]
 [0.324 0.419 0.526 0.419 1.    0.401 0.429 0.514]
 [0.344 0.381 0.394 0.381 0.401 1.    0.384 0.39 ]
 [0.348 0.539 0.478 0.488 0.429 0.384 1.    0.371]
 [0.474 0.437 0.542 0.612 0.514 0.39  0.371 1.   ]]


In [12]:
user_choice  = 'Puu no Puupuupuu'
ref_index = df[df.Title.str.contains(user_choice)].index
for index in ref_index:
    print(df.Title[index])
    print("index= {0}".format(index))


[Puu no Puupuupuu (Puuzaki Puuna)] Hitozukiai ga Nigate na Miboujin no Yukionna-san to Noroi no Yubiwa [English]
index= 0
[Puu no Puupuupuu] Karui Kimochi de Heya ni Ageta Gal to Hamemakuri!? [English] [SDTLs]
index= 2


In [14]:
similar__movies=list(enumerate(cosine_sim[4]))
sorted_similar__movies=sorted(similar__movies,key=lambda x:x[1],reverse=True)[1:]
x=sorted_similar__movies[:6]
num=1
for i in x:
    print("{1}:TITLE={0} Score:{2} ".format(df.Title[i[0]],num,i[1]*100))
    print("Link={0}".format(df.URL[i[0]]))
    print()
    num+=1

1:TITLE=(C84) [Aomizuan (ti, Toilet Komoru)] Chikan Shita Joshikousei to Sonogo, Musabori Au you na Doero Junai | The Schoolgirl Who Was Groped, and the Perverted Love They Shared Afterwards [English] {doujin-moe.us} Score:59.844374893127636 
Link=https://nhentai.net/g/107965

2:TITLE=[Aomizuan (Erodezain Koubou)] Kiniitta Chitsu ni Ikinari Nakadashi OK na Resort Shima 3 | Resort Island of Women Who Love It When You Cum Inside Them 3 [English] [Krizalid] Score:58.457785294165134 
Link=https://nhentai.net/g/157475

3:TITLE=[Aomizuan (Sasada Aki)] InCha Bishoujo wa, Tannin ni Okasarete mo Ikimakuru 3 | Introverted Beauty Gets Raped Over and Over by Her Homeroom Teacher 3 [English] [HentieBoyz] [Digital] Score:57.61659596980322 
Link=https://nhentai.net/g/368176

4:TITLE=[Aomizuan (Katsurai Yoshiaki)] InCha Bishoujo wa Tannin ni Okasarete mo Ikimakuru 2 | Introverted Beauty Gets Raped Over and Over by Her Homeroom Teacher 2 [English] [Digital] Score:55.91491340752627 
Link=https://nhentai